/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ICWFC;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import static ICWFC.TestClass.input;
import static ICWFC.TestClass.output;
import static ICWFC.TestClass.writeData;
import static com.sun.org.apache.xalan.internal.xsltc.compiler.util.Type.Int;
import java.awt.Color;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author THAMINA PRITY
 */
public class Home extends javax.swing.JFrame {
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();        
        conn = connectDb.ConnercrDB();
        FillComboHome();
        totalcount();
        totaltaka();
    }
    
    private void FillComboHome(){
    try {
        String sql = "SELECT\n" +
                    "customer.customername,\n" +
                    "car.carname,\n" +
                    "driver.drivername\n" +
                    "FROM\n" +
                    "customer\n" +
                    "INNER JOIN car ON customer.carid = car.carid\n" +
                    "INNER JOIN driver ON customer.driverid = driver.driverid";
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();
        
        while(rs.next()){
            String customername = rs.getString("customername");
            cmb_Customer.addItem(customername);
            
            String driverName = rs.getString("drivername");
            cmb_Driver.addItem(driverName);
            
            String carName = rs.getString("carname");
            cmb_Car.addItem(carName);           
            
            
           // String driver = rs.getString("drivername");
            //ComboBox_drivername.addItem(driver);
            
            
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    finally{
            try {
                //Close the database connection
                rs.close();
                pst.close();
                
            } catch (Exception e) {
            }
        }

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jMenuItem1 = new javax.swing.JMenuItem();
        jToggleButton1 = new javax.swing.JToggleButton();
        panel_CurrentLitreValue = new javax.swing.JPanel();
        txt_PreValue = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_Clear = new javax.swing.JButton();
        btn_Set = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        spinner_SetValue = new javax.swing.JSpinner();
        spinner_TotalTaka = new javax.swing.JSpinner();
        panel_TotalCount = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_Litre = new javax.swing.JLabel();
        lbl_Price = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbl_Total = new javax.swing.JLabel();
        panel_CustomerInfo = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_CustomerName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_CustomerPhone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_CustomerAddress = new javax.swing.JTextField();
        txt_DriverName = new javax.swing.JTextField();
        txt_DriverPhone = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_CarName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_CarNumber = new javax.swing.JTextField();
        btn_Reset = new javax.swing.JButton();
        btn_New = new javax.swing.JButton();
        btn_Edit = new javax.swing.JButton();
        panel_CustomerSelect = new javax.swing.JPanel();
        cmb_Customer = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        cmb_Driver = new javax.swing.JComboBox();
        cmb_Car = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        panel_TotalToday = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        txt_TotalToday = new javax.swing.JTextField();
        panel_TotalLifeTime = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txt_TotalLifeTime = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_Setting = new javax.swing.JMenu();
        item_Option = new javax.swing.JMenuItem();
        item_Owner = new javax.swing.JMenuItem();
        menu_Report = new javax.swing.JMenu();
        item_DailyReport = new javax.swing.JMenuItem();
        item_CustomerOrder = new javax.swing.JMenuItem();
        item_Search = new javax.swing.JMenuItem();
        menu_Help = new javax.swing.JMenu();
        item_Contact = new javax.swing.JMenuItem();
        item_About = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_CurrentLitreValue.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setBackground(java.awt.Color.white);
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Pre Value");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Set Value");

        btn_Clear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Clear.setText("Clear");
        btn_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClearActionPerformed(evt);
            }
        });

        btn_Set.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Set.setText("Set");
        btn_Set.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SetActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Total Taka");

        spinner_SetValue.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), null, Float.valueOf(1.0f)));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, spinner_SetValue, org.jdesktop.beansbinding.ELProperty.create("${model}"), spinner_SetValue, org.jdesktop.beansbinding.BeanProperty.create("model"));
        binding.setSourceNullValue(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), null, Float.valueOf(1.0f)));
        bindingGroup.addBinding(binding);

        spinner_TotalTaka.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), null, null, Float.valueOf(1.0f)));

        javax.swing.GroupLayout panel_CurrentLitreValueLayout = new javax.swing.GroupLayout(panel_CurrentLitreValue);
        panel_CurrentLitreValue.setLayout(panel_CurrentLitreValueLayout);
        panel_CurrentLitreValueLayout.setHorizontalGroup(
            panel_CurrentLitreValueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_CurrentLitreValueLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(panel_CurrentLitreValueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(panel_CurrentLitreValueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(spinner_SetValue, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(spinner_TotalTaka, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_CurrentLitreValueLayout.createSequentialGroup()
                        .addComponent(btn_Set)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Clear))
                    .addComponent(txt_PreValue))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        panel_CurrentLitreValueLayout.setVerticalGroup(
            panel_CurrentLitreValueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_CurrentLitreValueLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panel_CurrentLitreValueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(spinner_SetValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_CurrentLitreValueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txt_PreValue, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_CurrentLitreValueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(spinner_TotalTaka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_CurrentLitreValueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Clear)
                    .addComponent(btn_Set))
                .addGap(31, 31, 31))
        );

        panel_CurrentLitreValueLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {spinner_SetValue, spinner_TotalTaka, txt_PreValue});

        panel_TotalCount.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Litre:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Price:");

        lbl_Litre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_Litre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_Litre.setText("0000");

        lbl_Price.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_Price.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_Price.setText("0000");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Total:");

        lbl_Total.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_Total.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_Total.setText("0000");

        javax.swing.GroupLayout panel_TotalCountLayout = new javax.swing.GroupLayout(panel_TotalCount);
        panel_TotalCount.setLayout(panel_TotalCountLayout);
        panel_TotalCountLayout.setHorizontalGroup(
            panel_TotalCountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_TotalCountLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(panel_TotalCountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1)
                    .addGroup(panel_TotalCountLayout.createSequentialGroup()
                        .addGroup(panel_TotalCountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(34, 34, 34)
                        .addGroup(panel_TotalCountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Litre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_TotalCountLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lbl_Litre, lbl_Price, lbl_Total});

        panel_TotalCountLayout.setVerticalGroup(
            panel_TotalCountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_TotalCountLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panel_TotalCountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_TotalCountLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11))
                    .addGroup(panel_TotalCountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lbl_Price)
                        .addGroup(panel_TotalCountLayout.createSequentialGroup()
                            .addComponent(lbl_Litre)
                            .addGap(28, 28, 28))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(panel_TotalCountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(lbl_Total))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        panel_CustomerInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Cusomer Name:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Customer Phone:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Customer Address:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Driver Name:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Driver Phone:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Car name:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Car Number:");

        btn_Reset.setText("Reset");
        btn_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ResetActionPerformed(evt);
            }
        });

        btn_New.setText("New");
        btn_New.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NewActionPerformed(evt);
            }
        });

        btn_Edit.setText("Edit");

        javax.swing.GroupLayout panel_CustomerInfoLayout = new javax.swing.GroupLayout(panel_CustomerInfo);
        panel_CustomerInfo.setLayout(panel_CustomerInfoLayout);
        panel_CustomerInfoLayout.setHorizontalGroup(
            panel_CustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_CustomerInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_CustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_CustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panel_CustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panel_CustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(panel_CustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING))
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_CustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panel_CustomerInfoLayout.createSequentialGroup()
                        .addComponent(btn_New)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Edit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Reset))
                    .addGroup(panel_CustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_DriverName, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_CustomerName, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                        .addComponent(txt_CustomerAddress)
                        .addComponent(txt_CustomerPhone)
                        .addComponent(txt_CarNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_CarName, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_DriverPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        panel_CustomerInfoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txt_CarName, txt_CarNumber, txt_CustomerAddress, txt_CustomerName, txt_CustomerPhone, txt_DriverName, txt_DriverPhone});

        panel_CustomerInfoLayout.setVerticalGroup(
            panel_CustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_CustomerInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_CustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_CustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_CustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_CustomerPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_CustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_CustomerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_CustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_DriverName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_CustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_DriverPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(10, 10, 10)
                .addGroup(panel_CustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_CarName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_CustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_CarNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(38, 38, 38)
                .addGroup(panel_CustomerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Reset)
                    .addComponent(btn_New)
                    .addComponent(btn_Edit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_CustomerInfoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txt_CarName, txt_CarNumber, txt_CustomerAddress, txt_CustomerName, txt_CustomerPhone, txt_DriverName, txt_DriverPhone});

        panel_CustomerSelect.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Select Customer", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        cmb_Customer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmb_Customer.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));
        cmb_Customer.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmb_CustomerPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cmb_Customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_CustomerActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Driver :");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Customer: ");

        cmb_Driver.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmb_Driver.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));
        cmb_Driver.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmb_DriverPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        cmb_Car.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmb_Car.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));
        cmb_Car.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmb_CarPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Car :");

        javax.swing.GroupLayout panel_CustomerSelectLayout = new javax.swing.GroupLayout(panel_CustomerSelect);
        panel_CustomerSelect.setLayout(panel_CustomerSelectLayout);
        panel_CustomerSelectLayout.setHorizontalGroup(
            panel_CustomerSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_CustomerSelectLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_CustomerSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_CustomerSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_CustomerSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmb_Customer, 0, 360, Short.MAX_VALUE)
                    .addComponent(cmb_Driver, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmb_Car, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_CustomerSelectLayout.setVerticalGroup(
            panel_CustomerSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_CustomerSelectLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panel_CustomerSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(cmb_Customer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_CustomerSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(cmb_Driver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(panel_CustomerSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_Car, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_TotalToday.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Total Today");

        txt_TotalToday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TotalTodayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_TotalTodayLayout = new javax.swing.GroupLayout(panel_TotalToday);
        panel_TotalToday.setLayout(panel_TotalTodayLayout);
        panel_TotalTodayLayout.setHorizontalGroup(
            panel_TotalTodayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_TotalTodayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(txt_TotalToday, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        panel_TotalTodayLayout.setVerticalGroup(
            panel_TotalTodayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_TotalTodayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_TotalTodayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txt_TotalToday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panel_TotalLifeTime.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Total Lifetime: ");

        javax.swing.GroupLayout panel_TotalLifeTimeLayout = new javax.swing.GroupLayout(panel_TotalLifeTime);
        panel_TotalLifeTime.setLayout(panel_TotalLifeTimeLayout);
        panel_TotalLifeTimeLayout.setHorizontalGroup(
            panel_TotalLifeTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_TotalLifeTimeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_TotalLifeTime, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel_TotalLifeTimeLayout.setVerticalGroup(
            panel_TotalLifeTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_TotalLifeTimeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_TotalLifeTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txt_TotalLifeTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Connect");

        menu_Setting.setText("Setting");

        item_Option.setText("Option");
        item_Option.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_OptionActionPerformed(evt);
            }
        });
        menu_Setting.add(item_Option);

        item_Owner.setText("Owner");
        item_Owner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_OwnerActionPerformed(evt);
            }
        });
        menu_Setting.add(item_Owner);

        jMenuBar1.add(menu_Setting);

        menu_Report.setText("Report");

        item_DailyReport.setText("Daily Report");
        item_DailyReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_DailyReportActionPerformed(evt);
            }
        });
        menu_Report.add(item_DailyReport);

        item_CustomerOrder.setText("Customer's Order");
        item_CustomerOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_CustomerOrderActionPerformed(evt);
            }
        });
        menu_Report.add(item_CustomerOrder);

        item_Search.setText("Search");
        item_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_SearchActionPerformed(evt);
            }
        });
        menu_Report.add(item_Search);

        jMenuBar1.add(menu_Report);

        menu_Help.setText("Help");

        item_Contact.setText("Contact");
        item_Contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_ContactActionPerformed(evt);
            }
        });
        menu_Help.add(item_Contact);

        item_About.setText("About");
        item_About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_AboutActionPerformed(evt);
            }
        });
        menu_Help.add(item_About);

        jMenuBar1.add(menu_Help);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panel_CustomerInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panel_TotalToday, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel_TotalLifeTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel_TotalCount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(panel_CurrentLitreValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panel_CustomerSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(9, 9, 9)))))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_CurrentLitreValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel_CustomerSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(panel_TotalCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel_TotalToday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panel_TotalLifeTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(panel_CustomerInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void cmb_CustomerPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmb_CustomerPopupMenuWillBecomeInvisible
        try {            
            String tmpCustomer = (String)cmb_Customer.getSelectedItem();
            //String tmpDriver = (String) cmb_Driver.getSelectedItem();
            //String tmpCar = (String) cmb_Car.getSelectedItem();
            
            String sql = "SELECT\n" +
                        "customer.customername,\n" +
                        "customer.customerphone,\n" +
                        "customer.customeraddress,\n" +
                        "driver.drivername,\n" +
                        "driver.driverphone,\n" +
                        "car.carname,\n" +
                        "car.carnumber\n" +
                        "FROM\n" +
                        "customer\n" +
                        "INNER JOIN driver ON customer.driverid = driver.driverid\n" +
                        "INNER JOIN car ON customer.carid = car.carid\n" +
                        "WHERE\n" +
                        "customer.customername = ?";
                    
            pst = conn.prepareStatement(sql);
            pst.setString(1, tmpCustomer);
            //pst.setString(2, tmpDriver);
            //pst.setString(3, tmpCar);
            rs = pst.executeQuery();
            
            if(rs.next()){
                
            //All Customer Info
            String cmbHomeCustomerName = rs.getString("customername");
            txt_CustomerName.setText(cmbHomeCustomerName);
            String cmbHomeCustomerPhone = rs.getString("customerphone");
            txt_CustomerPhone.setText(cmbHomeCustomerPhone);
            String cmbHomeCustomerAddress = rs.getString("customeraddress");
            txt_CustomerAddress.setText(cmbHomeCustomerAddress);
            
            //All Driver Info\
            String cmbHomeDriverName = rs.getString("drivername");
            txt_DriverName.setText(cmbHomeDriverName);
            String cmbHomeDriverPhone = rs.getString("driverphone");
            txt_DriverPhone.setText(cmbHomeDriverPhone);
            
            //All Car Info
            String cmbHomeCarName = rs.getString("carname");
            txt_CarName.setText(cmbHomeCarName);
            String cmbHomeCarNumber = rs.getString("carnumber");
            txt_CarNumber.setText(cmbHomeCarNumber);
            }
            
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_cmb_CustomerPopupMenuWillBecomeInvisible

    private void btn_NewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NewActionPerformed
        NewCustomer nc = new NewCustomer();
        nc.setVisible(true);
    }//GEN-LAST:event_btn_NewActionPerformed

    private void btn_SetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SetActionPerformed
        
        try{
        //Variable for spinner            
        float setValue =  (float) spinner_SetValue.getValue();
        float totalTaka = (float) spinner_TotalTaka.getValue();
        
        System.out.println(setValue);
        System.out.println(totalTaka);
        //Sql for Price
        String pricesql = "SELECT\n" +
                            "productprice\n" +
                            "FROM\n" +
                            "product\n" +
                            "ORDER BY productprice ASC LIMIT 1";
                    
        pst = conn.prepareStatement(pricesql);
        rs = pst.executeQuery();
        
        //Get price from database 
        float price = rs.getFloat("productprice");
        String priceString = Float.toString(price);
        lbl_Price.setText(priceString);        
        
        //Getting data based on set Value or Taka
            if(setValue == 0 && totalTaka == totalTaka){                             
                spinner_SetValue.setValue(totalTaka/price);                
                
                DecimalFormat df = new DecimalFormat("###.##");
                String val = df.format(totalTaka/price); 
               
                
                //String setVal = Float.toString(val);
                lbl_Litre.setText(val);
                
                String totalTk = Float.toString(totalTaka);
                lbl_Total.setText(totalTk);
                
                
                txt_PreValue.setText(val);                
                txt_PreValue.setBackground(Color.red);
                
            } else if (totalTaka == 0 && setValue == setValue){
                spinner_TotalTaka.setValue(price * setValue);  
                
      
                String setVal = Float.toString(setValue);
                lbl_Litre.setText(setVal);               
                txt_PreValue.setText(setVal);
                txt_PreValue.setBackground(Color.red);
                
                float taka = price * setValue;  
                String totalTk = Float.toString(taka);
                lbl_Total.setText(totalTk);
               
                
                
                
            } else {
                JOptionPane.showMessageDialog(null, "Please Clear data and Input Set Value or Total Taka");
            }  
            
           } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }finally{
            try {
                //Close the database connection
                rs.close();
                pst.close();
                
            } catch (Exception e) {
            }
        
        }    
    }//GEN-LAST:event_btn_SetActionPerformed

    private void btn_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClearActionPerformed
       
        float resetValue = 0;
        
        spinner_SetValue.setValue(resetValue);       
        txt_PreValue.setText("000000");
        spinner_TotalTaka.setValue(resetValue);      
             
        lbl_Litre.setText("0000");
        lbl_Price.setText("0000");
        lbl_Total.setText("0000");
    }//GEN-LAST:event_btn_ClearActionPerformed

   /* 
    private void PlaceOrder(){
         
        try {
            String sql = "SELECT \n" +
                            "customerid\n" +
                            "FROM\n" +
                            "customer\n" +
                            "WHERE \n" +
                            "customername = 'Sarker'";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            if(rs.next()){ 
                String customerid = rs.getString("customerid");
                txt_CustomerName.setText(customerid);
                
                System.out.println(customerid);
                
                String ordersql = "INSERT INTO orders (\n" +
                                    "customerid,\n" +
                                    "orderdate,\n" +
                                    "total\n" +
                                    ")\n" +
                                    "VALUES\n" +
                                    "(customerid,date('now'),244,44)";
                pst = conn.prepareStatement(ordersql);
                rs = pst.executeQuery();
            }
            JOptionPane.showMessageDialog(null, "Your Data successfully Saved");
        } catch (SQLException e) {
             JOptionPane.showMessageDialog(null, e);
        }
        
    }
   */
    
    private void btn_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ResetActionPerformed
                
        try {            
            String customer = txt_CustomerName.getText();
            String driver = txt_DriverName.getText();
            String car = txt_CarName.getText();
            
            ////////////////////Check command line///////////////////////////
            System.out.println(customer);
            System.out.println(driver);
            System.out.println(car);
            
            String customersql = "SELECT\n" +
                                "customer.customerid,\n" +
                                "driver.driverid,\n" +
                                "car.carid,\n" +
                                "customer.customername,\n" +
                                "driver.drivername,\n" +
                                "car.carname\n" +
                                "FROM\n" +
                                "customer\n" +
                                "INNER JOIN driver ON customer.driverid = driver.driverid\n" +
                                "INNER JOIN car ON customer.carid = car.carid\n" +
                                "WHERE\n" +
                                "customer.customername = '"+customer+"'\n" +
                                "AND driver.drivername = '"+driver+"'\n" +
                                "AND car.carname = '"+car+"'";
            pst = conn.prepareStatement(customersql);
            rs = pst.executeQuery();
            
            
            String customerid = rs.getString("customerid");
            String driverid = rs.getString("driverid");
            String carid = rs.getString("carid");
            
            ////////////////////Check command line///////////////////////////
            System.out.println(customerid);
            System.out.println(driverid);
            System.out.println(carid);
   
              
            String pricesql = "SELECT\n" +
                            "productprice\n" +
                            "FROM\n" +
                            "product\n" +
                            "ORDER BY productprice ASC LIMIT 1";
                    
            pst = conn.prepareStatement(pricesql);
            rs = pst.executeQuery();
            
            float pricefloat = rs.getFloat("productprice");
            
            System.out.println(pricefloat);
 
            //Get total price from Total Taka
            float totalTaka = (float) spinner_TotalTaka.getValue();
            float total = (float) spinner_SetValue.getValue();
    
            
            //Inserting orders in the tabel
            String sql = "INSERT \n" +
                        "INTO orders (\n" +
                        "customerid,\n" + 
                        "driverid,\n"+
                        "carid,\n"+
                        "total,\n"+
                        "totaltaka\n"+
                        ")\n" +
                        "VALUES\n" +
                        "('"+customerid+"', '"+driverid+"', '"+carid+"','"+total+"', '"+totalTaka+"')";
            
            pst = conn.prepareStatement(sql);               
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "Your Data successfully Saved");
            
            totalcount();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }finally{
            try {
                //Close the database connection
                rs.close();
                pst.close();
                
            } catch (Exception e) {
            }
        }
        
        
        try {
            SerialClass obj = new SerialClass();
            int c = 0;
            obj.initialize();
            input = SerialClass.input;
            output = SerialClass.output;
            InputStreamReader Ir = new InputStreamReader(System.in);
            BufferedReader Br = new BufferedReader(Ir);
            
            writeData("DLBD+TL=?");
            String inputLine = input.readLine();
            System.out.println(inputLine);
            
            //jTextField1.setText(inputLine);
            
            //String to Character convert
            String str=inputLine;
            //lbl_Start.setText(str);
  
            obj.close();
            
            //Placing order
            
            
        } catch (IOException ex) {           
            
        }
    }//GEN-LAST:event_btn_ResetActionPerformed

    private void item_OwnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_OwnerActionPerformed
        Owner o = new Owner();
        o.setVisible(true);
    }//GEN-LAST:event_item_OwnerActionPerformed

    private void item_OptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_OptionActionPerformed
        OptionPanel op = new OptionPanel();
        op.setVisible(true);
    }//GEN-LAST:event_item_OptionActionPerformed

    private void cmb_DriverPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmb_DriverPopupMenuWillBecomeInvisible
        try {            
           // String tmpCustomer = (String)cmb_Customer.getSelectedItem();
            String tmpDriver = (String) cmb_Driver.getSelectedItem();
            //String tmpCar = (String) cmb_Car.getSelectedItem();
            
            String sql = "SELECT\n" +
                        "driver.drivername,\n" +
                        "driver.driverphone\n" +
                        "FROM\n" +
                        "driver\n" +
                        "WHERE\n" +
                        "driver.drivername = ?";
                    
            pst = conn.prepareStatement(sql);
           // pst.setString(1, tmpCustomer);
            pst.setString(1, tmpDriver);
            //pst.setString(3, tmpCar);
            rs = pst.executeQuery();
            
            if(rs.next()){                
        
            //All Driver Info\
            String cmbHomeDriverName = rs.getString("drivername");
            txt_DriverName.setText(cmbHomeDriverName);
            String cmbHomeDriverPhone = rs.getString("driverphone");
            txt_DriverPhone.setText(cmbHomeDriverPhone);
       
            }
            
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_cmb_DriverPopupMenuWillBecomeInvisible

    private void cmb_CarPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmb_CarPopupMenuWillBecomeInvisible
       try {            
           // String tmpCustomer = (String)cmb_Customer.getSelectedItem();
            //String tmpDriver = (String) cmb_Driver.getSelectedItem();
            String tmpCar = (String) cmb_Car.getSelectedItem();
            
            String sql = "SELECT\n" +
                        "car.carname,\n" +
                        "car.carnumber\n" +
                        "FROM\n" +
                        "car\n" +
                        "WHERE\n" +
                        "car.carname = ?";
                    
            pst = conn.prepareStatement(sql);
           // pst.setString(1, tmpCustomer);
            //pst.setString(1, tmpDriver);
            pst.setString(1, tmpCar);
            rs = pst.executeQuery();
            
            if(rs.next()){                
        
             //All Car Info
            String cmbHomeCarName = rs.getString("carname");
            txt_CarName.setText(cmbHomeCarName);
            String cmbHomeCarNumber = rs.getString("carnumber");
            txt_CarNumber.setText(cmbHomeCarNumber);
       
            }
            
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_cmb_CarPopupMenuWillBecomeInvisible

    private void item_AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_AboutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_item_AboutActionPerformed

    private void item_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_SearchActionPerformed
       Search s = new Search();
       s.setVisible(true);
    }//GEN-LAST:event_item_SearchActionPerformed

    private void item_DailyReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_DailyReportActionPerformed
        DailyReport dr = new DailyReport();
        dr.setVisible(true);
    }//GEN-LAST:event_item_DailyReportActionPerformed

    private void item_CustomerOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_CustomerOrderActionPerformed
          DailyOrder dailyO = new DailyOrder();
          dailyO.setVisible(true);
    }//GEN-LAST:event_item_CustomerOrderActionPerformed

    private void item_ContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_ContactActionPerformed
       Contact c = new Contact();
       c.setVisible(true);
    }//GEN-LAST:event_item_ContactActionPerformed

    private void cmb_CustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_CustomerActionPerformed
        
    }//GEN-LAST:event_cmb_CustomerActionPerformed

    private void txt_TotalTodayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TotalTodayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TotalTodayActionPerformed
    
    
    public void totaltaka(){
        try {
               String sql="SELECT\n" +                    
                       "sum(totaltaka)\n" +
                       "FROM\n" +
                       "orders\n";                     

               pst = conn.prepareStatement(sql);    
               rs = pst.executeQuery();

               if(rs.next()){
                   String sum = rs.getString("sum(totaltaka)");
                   txt_TotalToday.setText(sum);

               }
           } catch (Exception e) {
               JOptionPane.showMessageDialog(null, e);
           }
    
    }
    
    public void totalcount(){
        try {
               String sql="SELECT\n" +                    
                       "sum(total)\n" +
                       "FROM\n" +
                       "orders\n";                     

               pst = conn.prepareStatement(sql);    
               rs = pst.executeQuery();

               if(rs.next()){
                   String sum = rs.getString("sum(total)");
                   txt_TotalLifeTime.setText(sum);

               }
           } catch (Exception e) {
               JOptionPane.showMessageDialog(null, e);
           }
    
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Clear;
    private javax.swing.JButton btn_Edit;
    private javax.swing.JButton btn_New;
    private javax.swing.JButton btn_Reset;
    private javax.swing.JButton btn_Set;
    private javax.swing.JComboBox cmb_Car;
    private javax.swing.JComboBox cmb_Customer;
    private javax.swing.JComboBox cmb_Driver;
    private javax.swing.JMenuItem item_About;
    private javax.swing.JMenuItem item_Contact;
    private javax.swing.JMenuItem item_CustomerOrder;
    private javax.swing.JMenuItem item_DailyReport;
    private javax.swing.JMenuItem item_Option;
    private javax.swing.JMenuItem item_Owner;
    private javax.swing.JMenuItem item_Search;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lbl_Litre;
    private javax.swing.JLabel lbl_Price;
    private javax.swing.JLabel lbl_Total;
    private javax.swing.JMenu menu_Help;
    private javax.swing.JMenu menu_Report;
    private javax.swing.JMenu menu_Setting;
    private javax.swing.JPanel panel_CurrentLitreValue;
    private javax.swing.JPanel panel_CustomerInfo;
    private javax.swing.JPanel panel_CustomerSelect;
    private javax.swing.JPanel panel_TotalCount;
    private javax.swing.JPanel panel_TotalLifeTime;
    private javax.swing.JPanel panel_TotalToday;
    private javax.swing.JSpinner spinner_SetValue;
    private javax.swing.JSpinner spinner_TotalTaka;
    private javax.swing.JTextField txt_CarName;
    private javax.swing.JTextField txt_CarNumber;
    private javax.swing.JTextField txt_CustomerAddress;
    private javax.swing.JTextField txt_CustomerName;
    private javax.swing.JTextField txt_CustomerPhone;
    private javax.swing.JTextField txt_DriverName;
    private javax.swing.JTextField txt_DriverPhone;
    private javax.swing.JTextField txt_PreValue;
    private javax.swing.JTextField txt_TotalLifeTime;
    private javax.swing.JTextField txt_TotalToday;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
